// <auto-generated />
using System;
using Fibonacci.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fibonacci.Infrastructure.Migrations
{
    [DbContext(typeof(FibonacciContext))]
    [Migration("20220412161200_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Fibonacci.Domain.Models.FibonacciNumberModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("SequenceIndex")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("FibonacciNumbers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
